config:
  target: 'https://openweathermap.org'
  ensure:
    p95: 2000
  phases:
    - duration: 30
      arrivalRate: 3
  processor: "./customProcessor.js"          
scenarios:
  - flow:
    - function: "getRandomCityName"
    - log: "Sent FIND request with {{ cityNameEncode }}"
    - get:
        url: "/find?q={{ cityNameEncode }}"
        expect:
            - statusCode: 200
    - log: "Sent GET request with {{ cityName }}"
    - think: 1
    - get:
        url: "/data/2.5/find?type=like&sort=population&cnt=30&appid=439d4b804bc8187953eb36d2a8c26a02&_=1600071000335&q={{ cityName }}"
        capture:
          json: "$.list[0].id"
          as: "cityId"
        expect:
            - statusCode: 200
            - contentType: json    
    - think: 3        
    - log: "Sent GET request with cityName = {{ cityName }} - cityId = {{ cityId }}"
    - get:
        url: "/city/{{ cityId }}"
        expect:
            - statusCode: 200
    - think: 1
    - get:
        url: "/data/2.5/weather?id={{ cityId }}&units=metric&appid=439d4b804bc8187953eb36d2a8c26a02"
        expect:
            - statusCode: 200
            - contentType: json
    - think: 5